### PR TITLE
Port cake to use pg:backups 

### PR DESCRIPTION
**Pull request by davegriffiths**
NB - Everyone will need to update their cake and heroku gem

### CODE REVIEW

**Comment by matteodepalo** [comment]
:+1:

**Comment by toreriklinnerud** [comment]
Katherin and myself hit the issue that we still had the old heroku gem installed. Had to uninstall all versions of it before the cake command would use the toolbelt binary (supporting the new syntax) instead of the out of date gem version.

**Comment by JohnKellyFerguson** [comment]
Yea, I've had the same issue. We still bundle heroku in several of our repos, [brazil for example](https://github.com/alphasights/brazil/blob/master/Gemfile#L38), so it's very common to have the heroku gem on your local machine.

**Comment by davegriffiths** [comment]
Yeah, I pinged the chat at the time but looks like this isn't a great way of getting it done. Any suggestions?

**Pull request merged**
